services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      my-proxy-net:
        ipv4_address: 172.18.0.9

  srv_leakdetection:
    build:
      context: .
    image: srv_leakdetection:latest
    container_name: srv_leakdetection
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - redis
    networks:
      my-proxy-net:
        ipv4_address: 172.18.0.10

networks:
  my-proxy-net:
    name: aguas_network
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16