services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-proxy-net

  srv_leakdetection:
    build:
      context: .
    image: srv_leakdetection:latest
    container_name: srv_leakdetection
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - redis
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    name: aguas_network
    external: true